/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A row returned from a query */
export interface JsRow {
  columns: Array<string>
  values: Array<string | undefined | null>
}
/** Open an embedded icedb connection */
export declare function connect(dataDir: string): Connection
/** The main connection object */
export declare class Connection {
  /** Execute a SQL query and return the rows */
  query(sql: string): Array<JsRow>
  /** Execute a DML statement and return the number of affected rows */
  execute(sql: string): number
}
