[package]
name = "btree"
version = "0.1.0"
edition = "2021"

[dependencies]
storage = { path = "../storage" }
wal = { path = "../wal" }
thiserror = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
tempfile = "3"
